# Generated by Django 4.2.26 on 2025-11-14 07:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="investmentholding",
            name="unique_holding_per_user",
        ),
        migrations.RenameIndex(
            model_name="investmentholding",
            new_name="portfolio_i_user_id_2dec69_idx",
            old_name="portfolio_in_user_id_asset_region_idx",
        ),
        migrations.RenameIndex(
            model_name="investmentholding",
            new_name="portfolio_i_user_id_64dbab_idx",
            old_name="portfolio_in_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="projection",
            new_name="portfolio_p_user_id_820a27_idx",
            old_name="portfolio_pr_user_id_created_idx",
        ),
        migrations.RenameIndex(
            model_name="recurringinvestmentplan",
            new_name="portfolio_r_user_id_196a0a_idx",
            old_name="portfolio_re_user_id_idx",
        ),
        migrations.AlterUniqueTogether(
            name="investmentholding",
            unique_together={
                (
                    "user",
                    "account_type",
                    "asset_class",
                    "asset_region",
                    "asset_identifier",
                )
            },
        ),
    ]
