# Generated by Django 4.2.26 on 2025-11-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_remove_investmentholding_unique_holding_per_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentholding",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("NISA_TSUMITATE", "NISA (つみたて投資枠)"),
                    ("NISA_GROWTH", "NISA (成長投資枠)"),
                    ("GENERAL", "General Account"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recurringinvestmentplan",
            name="target_account_type",
            field=models.CharField(
                choices=[
                    ("NISA_TSUMITATE", "NISA (つみたて投資枠)"),
                    ("NISA_GROWTH", "NISA (成長投資枠)"),
                    ("GENERAL", "General Account"),
                ],
                max_length=20,
            ),
        ),
    ]
