# Generated by Django 4.2.26 on 2025-11-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_investmentholding_account_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringinvestmentplan",
            name="continue_if_limit_exceeded",
            field=models.BooleanField(
                default=False,
                help_text="If True, continue investing even after exceeding NISA limits (will use general account)",
            ),
        ),
    ]
