"""Minimal Django settings for development (generated by speckit implement)
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret-key-do-not-use-in-prod")

DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "192.168.50.51", "myapp.home", "*"]

# Reverse proxy support - Django will handle /stock_app prefix
FORCE_SCRIPT_NAME = os.environ.get("FORCE_SCRIPT_NAME", None)
USE_X_FORWARDED_HOST = True

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    # feature apps
    "portfolio",
    "accounts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]

WSGI_APPLICATION = "config.wsgi.application"

# Database configuration
# Use DATA_DIR for persistent storage in Docker
DATA_DIR = os.environ.get("DATA_DIR", str(BASE_DIR))
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(DATA_DIR, "db.sqlite3"),
    }
}

AUTH_PASSWORD_VALIDATORS = []

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files URL - works with or without FORCE_SCRIPT_NAME
if FORCE_SCRIPT_NAME:
    STATIC_URL = f"{FORCE_SCRIPT_NAME}/static/"
else:
    STATIC_URL = "/static/"

# Static files directory for collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# API routes should accept both with/without trailing slash; router handles optional slash.
# Keep APPEND_SLASH default behavior for non-API routes.

# DRF + drf-spectacular minimal config
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "config.authentication.CsrfExemptSessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

# CSRF & Session Cookie設定（開発環境用）
# 同一ホスト内の異なるポート間通信のため、SameSite=Laxで十分
# 本番環境では適切なCSRF保護とセキュリティ設定を実装してください
CSRF_COOKIE_SECURE = False  # HTTPの場合はFalse（開発環境）
CSRF_COOKIE_HTTPONLY = False  # JavaScriptからアクセス可能にする
CSRF_COOKIE_SAMESITE = 'Lax'  # 同一ホスト内の通信用
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_PATH = '/'  # 全てのパスでCookieを送信

SESSION_COOKIE_SECURE = False  # HTTPの場合はFalse（開発環境）
SESSION_COOKIE_HTTPONLY = True  # XSS攻撃対策
SESSION_COOKIE_SAMESITE = 'Lax'  # 同一ホスト内の通信用
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_DOMAIN = None  # Noneにして自動設定させる
SESSION_COOKIE_PATH = '/'  # 全てのパスでCookieを送信

# セッションの有効期限
SESSION_COOKIE_AGE = 86400  # 24時間

SPECTACULAR_SETTINGS = {
    "TITLE": "Portfolio Analysis API",
    "VERSION": "1.0.0",
    "SERVERS": [
        {
            "url": "http://localhost:8000/api/v1",
            "description": "Local development server",
        }
    ],
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "http://192.168.50.51:3001",
    "http://myapp.home:3001",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "http://192.168.50.51:3001",
    "http://192.168.50.51",
    "http://myapp.home:3001",
    "http://myapp.home",
]
CSRF_USE_SESSIONS = False  # Store CSRF token in cookie, not session

# CSRF failure logging
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.security.csrf': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}
